---
- name: MEDIUM | RHEL-08-010374 | RHEL 8 must enable kernel parameters to enforce discretionary access control on hardlinks.
  ansible.posix.sysctl:
    name: fs.protected_hardlinks
    value: "1"
    state: present
    sysctl_file: /etc/sysctl.d/99-sysctl.conf
    sysctl_set: true

  when:
    - rhel_08_010374
  tags:
    - RHEL-08-010374
