---
- name: MEDIUM | RHEL-08-010210 | The RHEL 8 /var/log/messages file must have mode 0640 or less permissive.
  ansible.builtin.file:
    path: /var/log/messages
    mode: u-x,g-wx,o-rwx

  when:
    - rhel_08_010210
  tags:
    - RHEL-08-010210
