---
- name: MEDIUM | RHEL-08-040286 | RHEL 8 must enable hardening for the Berkeley Packet Filter Just-in-time compiler.
  ansible.posix.sysctl:
    name: net.core.bpf_jit_harden
    value: "2"
    state: present
    sysctl_file: /etc/sysctl.d/99-sysctl.conf
    sysctl_set: true

  when:
    - rhel_08_040286
  tags:
    - RHEL-08-040286
