---
- name: MEDIUM | RHEL-08-010230 | The RHEL 8 /var/log/messages file must be group-owned by root.
  ansible.builtin.file:
    path: /var/log/messages
    group: root

  when:
    - rhel_08_010230
  tags:
    - RHEL-08-010230
