---
- name: MEDIUM | RHEL-08-040282 | RHEL 8 must restrict usage of ptrace to descendant processes.
  ansible.posix.sysctl:
    name: kernel.yama.ptrace_scope
    value: "1"
    state: present
    sysctl_file: /etc/sysctl.d/99-sysctl.conf
    sysctl_set: true

  when:
    - rhel_08_040282
  tags:
    - RHEL-08-040282
