---
- name: MEDIUM | RHEL-08-040261 | RHEL 8 must not accept router advertisements on all IPv6 interfaces.
  ansible.posix.sysctl:
    name: net.ipv6.conf.all.accept_ra
    value: "0"
    state: present
    sysctl_file: /etc/sysctl.d/99-sysctl.conf
    sysctl_set: true

  when:
    - rhel_08_040261
  tags:
    - RHEL-08-040261
