---
- name: MEDIUM | RHEL-08-020140 | RHEL 8 must require the maximum number of repeating characters of the same character class be limited to four when passwords are
    changed.
  ansible.builtin.lineinfile:
    path: /etc/security/pwquality.conf
    regexp: ^#?\s*maxclassrepeat
    line: maxclassrepeat = {{rhel8stig_password_complexity.maxclassrepeat|default('4')}}
    state: present

  when:
    - rhel_08_020140
  tags:
    - RHEL-08-020140
