---
- name: MEDIUM | RHEL-08-040210 | RHEL 8 must prevent IPv6 Internet Control Message Protocol (ICMP) redirect messages from being accepted.
  ansible.posix.sysctl:
    name: net.ipv6.conf.default.accept_redirects
    value: "0"
    state: present
    sysctl_file: /etc/sysctl.d/99-sysctl.conf
    sysctl_set: true

  when:
    - rhel_08_040210
  tags:
    - RHEL-08-040210
