---
- name: MEDIUM | RHEL-08-010650 | MANUAL FIX | RHEL 8 must prevent files with the setuid and setgid bit set from being executed on file systems that are imported
    via Network File System (NFS).
  ansible.builtin.debug:
    msg: Manual Lockdown Required | The nosuid option must be added to all mounted NFS shares.

  when:
    - rhel_08_010650
  tags:
    - RHEL-08-010650
    - manual_fix
