---
- name: MEDIUM | RHEL-08-010220 | The RHEL 8 /var/log/messages file must be owned by root.
  ansible.builtin.file:
    path: /var/log/messages
    owner: root

  when:
    - rhel_08_010220
  tags:
    - RHEL-08-010220
