---
- block:
    - name: MEDIUM | RHEL-08-010780 | All RHEL 8 local files and directories must have a valid owner. | Part 1 of 2
      ansible.builtin.shell: find / -path /proc -prune -path /sys -prune -fstype xfs -nouser
      register: noowner_results
      changed_when: false
      failed_when: false

    - name: MEDIUM | RHEL-08-010780 | All RHEL 8 local files and directories must have a valid owner. | Part 2 of 2
      ansible.builtin.file:
        path: "{{ item }}"
        owner: root
        group: root
      with_items: "{{ noowner_results.stdout_lines }}"

  when:
    - rhel_08_010780
  tags:
    - RHEL-08-010780
