---
- name: MEDIUM | RHEL-08-040260 | RHEL 8 must not be performing packet forwarding unless the system is a router.
  ansible.posix.sysctl:
    name: net.ipv6.conf.all.forwarding
    value: "0"
    state: present
    sysctl_file: /etc/sysctl.d/99-sysctl.conf
    sysctl_set: true

  when:
    - rhel_08_040260
    - not rhel8stig_router
  tags:
    - RHEL-08-040260
