---
- name: MEDIUM | RHEL-08-040259 | RHEL 8 must not enable IPv4 packet forwarding unless the system is a router.
  ansible.posix.sysctl:
    name: net.ipv4.conf.all.forwarding
    value: "0"
    state: present
    sysctl_file: /etc/sysctl.d/99-sysctl.conf
    sysctl_set: true

  when:
    - rhel_08_040259
    - not rhel8stig_router
  tags:
    - RHEL-08-040259
