---
- block:
    - name: MEDIUM | RHEL-08-040129 RHEL-08-040130 RHEL-08-040131 | RHEL 8 must mount /var/log/audit with the nosuid, noexec, nodev options. | Part 1 of 2
      ansible.posix.mount:
        path: /var/log/audit
        src: UUID={{ var_log_audit_mount.uuid }}
        fstype: "{{ var_log_audit_mount.fstype }}"
        opts: "{{ var_log_audit_mount.options }},nosuid,noexec,nodev"
        state: mounted

    - name: MEDIUM | RHEL-08-040129 RHEL-08-040130 RHEL-08-040131 | RHEL 8 must mount /var/log/audit with the nosuid, noexec, nodev options. | Part 2 of 2
      ansible.builtin.command: mount /var/log/audit -o remount,nosuid,noexec,nodev

  when:
    - rhel_08_040129 or rhel_08_040130 or rhel_08_040131
    - ansible_mounts | selectattr('mount', 'match', '^/var/log/audit$') | list | length != 0
    - "'nosuid' not in var_log_audit_mount.options"
    - "'noexec' not in var_log_audit_mount.options"
    - "'nodev' not in var_log_audit_mount.options"
  vars:
    var_log_audit_mount: "{{ ansible_mounts | json_query('[?mount == `/var/log/audit`] | [0]') }}"
  tags:
    - RHEL-08-040129
    - RHEL-08-040130
    - RHEL-08-040131
