---
- name: MEDIUM | RHEL-08-030060 | The RHEL 8 audit system must take appropriate action when the audit storage volume is full.
  ansible.builtin.lineinfile:
    path: /etc/audit/auditd.conf
    regexp: ^#?\s*disk_full_action
    line: disk_full_action = {{ rhel8stig_disk_full_action }}
    state: present
  notify: Restart auditd

  when:
    - rhel_08_030060
  tags:
    - RHEL-08-030060
