---
- name: MEDIUM | RHEL-08-040161 | RHEL 8 must force a frequent session key renegotiation for SSH connections to the server.
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: ^#?\s*RekeyLimit.*
    line: RekeyLimit 1G 1h
    state: present
    validate: /usr/sbin/sshd -tf %s
  notify: Restart OpenSSH

  when:
    - rhel_08_040161
  tags:
    - RHEL-08-040161
