---
- block:
    - name: MEDIUM | RHEL-08-040132 RHEL-08-040133 RHEL-08-040134 | RHEL 8 must mount /var/tmp with the nosuid, noexec, nodev options. | Part 1 of 2
      ansible.posix.mount:
        path: /var/tmp
        src: UUID={{ var_tmp_mount.uuid }}
        fstype: "{{ var_tmp_mount.fstype }}"
        opts: "{{ var_tmp_mount.options }},nosuid,noexec,nodev"
        state: mounted

    - name: MEDIUM | RHEL-08-040132 RHEL-08-040133 RHEL-08-040134 | RHEL 8 must mount /var/tmp with the nosuid, noexec, nodev options. | Part 2 of 2
      ansible.builtin.command: mount /var/tmp -o remount,nosuid,noexec,nodev

  when:
    - rhel_08_040132 or rhel_08_040133 or rhel_08_040134
    - ansible_mounts | selectattr('mount', 'match', '^/var/tmp$') | list | length != 0
    - "'nosuid' not in var_tmp_mount.options"
    - "'noexec' not in var_tmp_mount.options"
    - "'nodev' not in var_tmp_mount.options"
  vars:
    var_tmp_mount: "{{ ansible_mounts | json_query('[?mount == `/var/tmp`] | [0]') }}"
  tags:
    - RHEL-08-040132
    - RHEL-08-040133
    - RHEL-08-040134
