---
- block:
    - name: MEDIUM | RHEL-08-010310 | RHEL 8 system commands must be owned by root. | Part 1 of 2
      ansible.builtin.shell: find -L /bin /sbin /usr/bin /usr/sbin /usr/local/bin /usr/local/sbin -uid +999
      register: system_commands
      changed_when: system_commands.stdout != ""

    - name: MEDIUM | RHEL-08-010310 | RHEL 8 system commands must be owned by root. | Part 2 of 2
      ansible.builtin.file:
        path: "{{ item }}"
        owner: root
      with_items: "{{ system_commands.stdout_lines }}"

  when:
    - rhel_08_010310
  tags:
    - RHEL-08-010310
