---
- name: MEDIUM | RHEL-08-020190 | RHEL 8 passwords for new users or password changes must have a 24 hours/1 day minimum password lifetime restriction in /etc/logins.def.
  ansible.builtin.lineinfile:
    path: /etc/login.defs
    regexp: ^#PASS_MIN_DAYS.*|^PASS_MIN_DAYS.*
    line: PASS_MIN_DAYS {{rhel8stig_login_defaults.pass_min_days|default('1')}}
    state: present

  when:
    - rhel_08_020190
  tags:
    - RHEL-08-020190
