---
- name: MEDIUM | RHEL-08-030030 | The RHEL 8 Information System Security Officer (ISSO) and System Administrator (SA) (at a minimum) must have mail aliases to be
    notified of an audit processing failure.
  ansible.builtin.lineinfile:
    path: /etc/aliases
    regexp: ^#?\s*postmaster
    line: "postmaster:\troot"
    state: present

  when:
    - rhel_08_030030
  tags:
    - RHEL-08-030030
