---
- name: MEDIUM | RHEL-08-010730 | All RHEL 8 local interactive user home directories must have mode 0750 or less permissive.
  ansible.builtin.file:
    path: "{{ item.dir }}"
    mode: "{{ rhel8stig_homedir_mode }}"
  with_items: "{{ rhel8stig_passwd }}"
  loop_control:
    label: "{{ rhel8stig_passwd_label }}"

  when:
    - rhel_08_010730
    - item.uid >= 1000
    - item.uid < 65534
  tags:
    - RHEL-08-010730
