---
- name: MEDIUM | RHEL-08-010630 | MANUAL FIX | RHEL 8 must prevent files with the setuid and setgid bit set from being executed on file systems that are imported
    via Network File System (NFS).
  ansible.builtin.debug:
    msg: Manual Lockdown Required | The noexec option must be added to all mounted NFS shares.

  when:
    - rhel_08_010630
  tags:
    - RHEL-08-010630
    - manual_fix
