---
- block:
    - name: MEDIUM | RHEL-08-010180 | All RHEL 8 public directories must be owned by root or a system account to prevent unauthorized and unintended information transferred
        via shared system resources. | Part 1 of 2
      ansible.builtin.shell: find {{ rhel8stig_local_mounts | join(' ') }} -xdev -not -path "/proc*" -not -path "/sys*" -not -path "*/.local/share/containers*" -type
        d -perm -0002 -uid +999 -gid +999
      register: public_directories
      changed_when: public_directories.stdout != ""

    - name: MEDIUM | RHEL-08-010180 | All RHEL 8 public directories must be owned by root or a system account to prevent unauthorized and unintended information transferred
        via shared system resources. | Part 2 of 2
      ansible.builtin.file:
        path: "{{ item }}"
        owner: root
        group: root
      with_items: "{{ public_directories.stdout_lines }}"

  when:
    - rhel_08_010180
  tags:
    - RHEL-08-010180
