---
- name: MEDIUM | RHEL-08-010640 | MANUAL FIX | RHEL 8 must prevent special devices on file systems that are imported via Network File System (NFS).
  ansible.builtin.debug:
    msg: Manual Lockdown Required | The nodev option must be added to all mounted NFS shares.

  when:
    - rhel_08_010640
  tags:
    - RHEL-08-010640
    - manual_fix
