---
- name: MEDIUM | RHEL-08-040020 | RHEL 8 must cover or disable the built-in or attached camera when not in use.
  ansible.builtin.lineinfile:
    path: /etc/modprobe.d/blacklist.conf
    create: true
    owner: root
    group: root
    mode: 0644
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  with_items:
    - { regexp: "^#?\\s*install uvcvideo.*", line: install uvcvideo /bin/true }
    - { regexp: "^#?\\s*blacklist uvcvideo", line: blacklist uvcvideo }

  when:
    - rhel_08_040020
  tags:
    - RHEL-08-040020
