---
- name: MEDIUM | RHEL-08-010410 | RHEL 8 must accept Personal Identity Verification (PIV) credentials.
  ansible.builtin.dnf:
    name: opensc
    state: latest

  when:
    - rhel_08_010410
    - rhel8stig_mfa
  tags:
    - RHEL-08-010410
    - mfa
