---
- name: MEDIUM | RHEL-08-040285 | RHEL 8 must use reverse path filtering on all IPv4 interfaces.
  ansible.posix.sysctl:
    name: net.ipv4.conf.all.rp_filter
    value: "1"
    state: present
    sysctl_file: /etc/sysctl.d/99-sysctl.conf
    sysctl_set: true

  when:
    - rhel_08_040285
  tags:
    - RHEL-08-040285
