---
- name: MEDIUM | RHEL-08-010430 | RHEL 8 must implement address space layout randomization (ASLR) to protect its memory from unauthorized code execution.
  ansible.posix.sysctl:
    name: kernel.randomize_va_space
    value: "2"
    state: present
    sysctl_file: /etc/sysctl.d/99-sysctl.conf
    sysctl_set: true

  when:
    - rhel_08_010430
  tags:
    - RHEL-08-010430
