---
- name: MEDIUM | RHEL-08-010750 | All RHEL 8 local interactive user home directories defined in the /etc/passwd file must exist.
  ansible.builtin.file:
    path: "{{ item.dir }}"
    state: directory
  with_items: "{{ rhel8stig_passwd }}"
  loop_control:
    label: "{{ rhel8stig_passwd_label }}"

  when:
    - rhel_08_010750
    - item.uid >= 1000
    - item.uid < 65534
  tags:
    - RHEL-08-010750
