---
- name: MEDIUM | RHEL-08-040280 | RHEL 8 must ignore IPv6 Internet Control Message Protocol (ICMP) redirect messages.
  ansible.posix.sysctl:
    name: net.ipv6.conf.all.accept_redirects
    value: "0"
    state: present
    sysctl_file: /etc/sysctl.d/99-sysctl.conf
    sysctl_set: true

  when:
    - rhel_08_040280
  tags:
    - RHEL-08-040280
