---
- name: MEDIUM | RHEL-08-020050 | RHEL 8 must be able to initiate directly a session lock for all connection types using smartcard when the smartcard is removed.
  ansible.builtin.lineinfile:
    path: /etc/dconf/db/distro.d/20-authselect
    line: "{{ item }}"
  with_items:
    - "[org/gnome/settings-daemon/peripherals/smartcard]"
    - removal-action='lock-screen'
  notify: Update dconf

  when:
    - rhel_08_020050
    - rhel8stig_gui
    - rhel8stig_mfa
  tags:
    - RHEL-08-020050
    - gui
