---
- name: MEDIUM | RHEL-08-030620 | RHEL 8 audit tools must have a mode of 0755 or less permissive.
  ansible.builtin.file:
    path: "{{ item }}"
    state: file
    mode: g-w,o-w
  with_items:
    - /sbin/auditctl
    - /sbin/aureport
    - /sbin/ausearch
    - /sbin/autrace
    - /sbin/auditd
    - /sbin/rsyslogd
    - /sbin/augenrules

  when:
    - rhel_08_030620
  tags:
    - RHEL-08-030620
