---
- block:
    - name: MEDIUM | RHEL-08-010120 | RHEL 8 must employ FIPS 140-2 approved cryptographic hashing algorithms for all stored passwords. | Part 1 of 2
      ansible.builtin.shell: "cut -d: -f1,2 /etc/shadow | grep -v '!!' | grep -v '*' | grep -v ':$6'"
      register: shadow_results
      changed_when: false
      failed_when: false

    - name: MEDIUM | RHEL-08-010120 | RHEL 8 must employ FIPS 140-2 approved cryptographic hashing algorithms for all stored passwords. | Part 2 of 2
      ansible.builtin.debug:
        msg: The shadow file entry {{ shadow_results.stdout_lines }} does not meeting FIPS 140-2 hashing requirements
      when: shadow_results.stdout_lines | length > 0

  when:
    - rhel_08_010120
  tags:
    - RHEL-08-010120
