---
- block:
    - name: MEDIUM | RHEL-08-010351 | RHEL 8 library directories must be group-owned by root or a system account. | Part 1 of 3
      ansible.builtin.shell: find /lib /lib64 /usr/lib /usr/lib64 ! -group root -type d
      changed_when: false
      failed_when: false
      check_mode: false
      register: directories

    - name: MEDIUM | RHEL-08-010351 | RHEL 8 library directories must be group-owned by root or a system account. | Part 2 of 3
      ansible.builtin.debug:
        msg:
          - Alert! There are library directories not group-owned by root
          - To conform to STIG standards, please review these directories and set the group-owner to be root
          - "{{ directories.stdout_lines }}"
      when:
        - directories.stdout | length > 0

    - name: MEDIUM | RHEL-08-010351 | RHEL 8 library directories must be group-owned by root or a system account. | Part 3 of 3
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        group: root
      with_items:
        - "{{ directories.stdout_lines }}"
      when:
        - directories.stdout | length > 0

  when:
    - rhel_08_010351
  tags:
    - RHEL-08-010351
