---
- name: MEDIUM | RHEL-08-010830 | Unattended or automatic logon to RHEL 8 via ssh must not be allowed.
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: ^#PermitUserEnvironment.*|^PermitUserEnvironment.*
    line: PermitUserEnvironment no
    state: present
    validate: /usr/sbin/sshd -tf %s
  notify: Restart OpenSSH

  when:
    - rhel_08_010830
  tags:
    - RHEL-08-010830
