---
- block:
    - name: MEDIUM | RHEL-08-010350 | RHEL 8 library files must be group-owned by root. | Part 1 of 2
      ansible.builtin.shell: find -L /lib /lib64 /usr/lib /usr/lib64 ! -group root
      register: system_libraries
      changed_when: system_libraries.stdout != ""

    - name: MEDIUM | RHEL-08-010350 | RHEL 8 library files must be group-owned by root. | Part 2 of 2
      ansible.builtin.file:
        path: "{{ item }}"
        group: root
      with_items: "{{ system_libraries.stdout_lines }}"

  when:
    - rhel_08_010350
  tags:
    - RHEL-08-010350
