---
- name: MEDIUM | RHEL-08-020351 | RHEL 8 must define default permissions for all authenticated users in such a way that the user can only read and modify their own
    files.
  ansible.builtin.lineinfile:
    path: /etc/login.defs
    regexp: ^#UMASK.*|^UMASK.*
    line: UMASK        {{rhel8stig_login_defaults.umask|default('077')}}
    state: present

  when:
    - rhel_08_020351
  tags:
    - RHEL-08-020351
