---
- block:
    - name: MEDIUM | RHEL-08-010330 | HEL 8 library files must have mode 0755 or less permissive. | Part 1 of 2
      ansible.builtin.shell: find -L /lib /lib64 /usr/lib /usr/lib64 -perm /022 -type f
      register: system_libraries
      changed_when: system_libraries.stdout != ""

    - name: MEDIUM | RHEL-08-010330 | HEL 8 library files must have mode 0755 or less permissive. | Part 2 of 2
      ansible.builtin.file:
        path: "{{ item }}"
        mode: g-w,o-w
      with_items: "{{ system_libraries.stdout_lines }}"

  when:
    - rhel_08_010330
  tags:
    - RHEL-08-010330
