---
- block:
    - name: MEDIUM | RHEL-08-010710 | All RHEL 8 world-writable directories must be owned by root, sys, bin, or an application group. | Part 1 of 2
      ansible.builtin.shell: find / -xdev -not -path "*/.local/share/containers*" -type d -perm -0002 -gid +999 -print
      register: world_writable
      changed_when: world_writable.stdout != ""

    - name: MEDIUM | RHEL-08-010710 | All RHEL 8 world-writable directories must be owned by root, sys, bin, or an application group. | Part 2 of 2
      ansible.builtin.file:
        path: "{{ item }}"
        group: root
      with_items: "{{ world_writable.stdout_lines }}"

  when:
    - rhel_08_010710
  tags:
    - RHEL-08-010710
