---
- name: MEDIUM | RHEL-08-010522 | The RHEL 8 SSH daemon must not allow GSSAPI authentication, except to fulfill documented and validated mission requirements.
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: ^#?\s*GSSAPIAuthentication.*
    line: GSSAPIAuthentication no
    state: present
    validate: /usr/sbin/sshd -tf %s
  notify: Restart OpenSSH

  when:
    - rhel_08_010522
    - not rhel8stig_gssapi
  tags:
    - RHEL-08-010522
