---
- name: MEDIUM | RHEL-08-010671 | RHEL 8 must disable the kernel.core_pattern.
  ansible.posix.sysctl:
    name: kernel.core_pattern
    value: " |/bin/false"
    state: present
    sysctl_file: /etc/sysctl.d/99-sysctl.conf
    sysctl_set: true

  when:
    - rhel_08_010671
  tags:
    - RHEL-08-010671
