---
- name: MEDIUM | RHEL-08-010152 | RHEL 8 operating systems must require authentication upon booting into emergency mode.
  ansible.builtin.lineinfile:
    path: /usr/lib/systemd/system/emergency.service
    regexp: ^#?\s*ExecStart.*
    line: ExecStart=-/usr/lib/systemd/systemd-sulogin-shell emergency
    state: present

  when:
    - rhel_08_010152
  tags:
    - RHEL-08-010152
