---
- name: MEDIUM | RHEL-08-040111 | RHEL 8 must be configured to disable USB mass storage.
  ansible.builtin.lineinfile:
    path: /etc/modprobe.d/blacklist.conf
    create: true
    owner: root
    group: root
    mode: 0644
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  with_items:
    - { regexp: "^#?\\s*install bluetooth.*", line: install bluetooth /bin/true }
    - { regexp: "^#?\\s*blacklist bluetooth", line: blacklist bluetooth }

  when:
    - rhel_08_040111
    - not rhel8stig_bluetooth
  tags:
    - RHEL-08-040111
