---
- block:
    - name: MEDIUM | RHEL-08-010320 | RHEL 8 system commands must be group-owned by root or a system account. | Part 1 of 2
      ansible.builtin.shell: find -L /bin /sbin /usr/bin /usr/sbin /usr/local/bin /usr/local/sbin ! -group root
      args:
        warn: false
      register: system_commands
      changed_when: system_commands.stdout != ""

    - name: MEDIUM | RHEL-08-010320 | RHEL 8 system commands must be group-owned by root or a system account. | Part 2 of 2
      ansible.builtin.file:
        path: "{{ item }}"
        group: root
      with_items: "{{ system_commands.stdout_lines }}"

  when:
    - rhel_08_010320
  tags:
    - RHEL-08-010320
