---
- name: MEDIUM | RHEL-08-020160 | RHEL 8 must require the change of at least four character classes when passwords are changed.
  ansible.builtin.lineinfile:
    path: /etc/security/pwquality.conf
    regexp: ^#?\s*minclass
    line: minclass = {{rhel8stig_password_complexity.minclass|default('4')}}
    state: present

  when:
    - rhel_08_020160
  tags:
    - RHEL-08-020160
