---
- name: MEDIUM | RHEL-08-010201 | The RHEL 8 SSH daemon must be configured with a timeout interval.
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: ^#?\s*ClientAliveInterval.*
    line: ClientAliveInterval 600
    state: present
    validate: /usr/sbin/sshd -tf %s
  notify: Restart OpenSSH

  when:
    - rhel_08_010201
  tags:
    - RHEL-08-010201
