---
- name: MEDIUM | RHEL-08-010151 | RHEL 8 operating systems must require authentication upon booting into rescue modes.
  ansible.builtin.lineinfile:
    path: /usr/lib/systemd/system/rescue.service
    regexp: ^#?\s*ExecStart.*
    line: ExecStart=-/usr/lib/systemd/systemd-sulogin-shell rescue
    state: present

  when:
    - rhel_08_010151
  tags:
    - RHEL-08-010151
