---
- name: MEDIUM | RHEL-08-040249 | RHEL 8 must not forward IPv4 source-routed packets by default.
  ansible.posix.sysctl:
    name: net.ipv4.conf.default.accept_source_route
    value: "0"
    state: present
    sysctl_file: /etc/sysctl.d/99-sysctl.conf
    sysctl_set: true

  when:
    - rhel_08_040249
  tags:
    - RHEL-08-040249
