---
- name: MEDIUM | RHEL-08-040270 | RHEL 8 must not accept router advertisements on all IPv6 interfaces by default.
  ansible.posix.sysctl:
    name: net.ipv4.conf.default.send_redirects
    value: "0"
    state: present
    sysctl_file: /etc/sysctl.d/99-sysctl.conf
    sysctl_set: true

  when:
    - rhel_08_040270
  tags:
    - RHEL-08-040270
