---
- name: MEDIUM | RHEL-08-030040 | The RHEL 8 System must take appropriate action when an audit processing failure occurs.
  ansible.builtin.lineinfile:
    path: /etc/audit/auditd.conf
    regexp: ^#?\s*disk_error_action
    line: disk_error_action = {{ rhel8stig_disk_error_action }}
    state: present
  notify: Restart auditd

  when:
    - rhel_08_030040
  tags:
    - RHEL-08-030040
