---
- name: MEDIUM | RHEL-08-040279 | RHEL 8 must ignore IPv4 Internet Control Message Protocol (ICMP) redirect messages.
  ansible.posix.sysctl:
    name: net.ipv4.conf.all.accept_redirects
    value: "0"
    state: present
    sysctl_file: /etc/sysctl.d/99-sysctl.conf
    sysctl_set: true

  when:
    - rhel_08_040279
  tags:
    - RHEL-08-040279
