---
- name: MEDIUM | RHEL-08-010520 | The RHEL 8 SSH daemon must not allow authentication using known host’s authentication.
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: ^#IgnoreUserKnownHosts.*|^IgnoreUserKnownHosts.*
    line: IgnoreUserKnownHosts yes
    state: present
    validate: /usr/sbin/sshd -tf %s
  notify: Restart OpenSSH

  when:
    - rhel_08_010520
  tags:
    - RHEL-08-010520
