---
- name: MEDIUM | RHEL-08-040220 | RHEL 8 must not send Internet Control Message Protocol (ICMP) redirects.
  ansible.posix.sysctl:
    name: net.ipv4.conf.all.send_redirects
    value: "0"
    state: present
    sysctl_file: /etc/sysctl.d/99-sysctl.conf
    sysctl_set: true

  when:
    - rhel_08_040220
  tags:
    - RHEL-08-040220
