---
- name: MEDIUM | RHEL-08-020150 | RHEL 8 must require the maximum number of repeating characters be limited to three when passwords are changed.
  ansible.builtin.lineinfile:
    path: /etc/security/pwquality.conf
    regexp: ^#?\s*maxrepeat
    line: maxrepeat = {{rhel8stig_password_complexity.maxrepeat|default('3')}}
    state: present

  when:
    - rhel_08_020150
  tags:
    - RHEL-08-020150
