---
- name: MEDIUM | RHEL-08-010200 | RHEL 8 must be configured so that all network connections associated with SSH traffic are terminated at the end of the session or
    after 10 minutes of inactivity, except to fulfill documented and validated mission requirements.
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: ^#?\s*ClientAliveCountMax.*
    line: ClientAliveCountMax 1
    state: present
    validate: /usr/sbin/sshd -tf %s
  notify: Restart OpenSSH

  when:
    - rhel_08_010200
  tags:
    - RHEL-08-010200
