---
- block:
    - name: MEDIUM | RHEL-08-010010 | RHEL 8 vendor packaged system security patches and updates must be installed and up to date. | Part 1 of 2
      ansible.builtin.dnf:
        list: updates
      register: update_status

    - name: MEDIUM | RHEL-08-010010 | RHEL 8 vendor packaged system security patches and updates must be installed and up to date. | Part 2 of 2
      ansible.builtin.debug:
        msg: System is in need of Patches
      changed_when: true
      when: update_status.results[0].name is defined

  when:
    - rhel_08_010010
  tags:
    - RHEL-08-010010
