---
- name: MEDIUM | RHEL-08-020040 | RHEL 8 must enable a user session lock until that user re-establishes access using established identification and authentication
    procedures for command line sessions. Part 1 of 2
  ansible.builtin.lineinfile:
    path: /etc/tmux.conf
    line: set -g lock-command vlock
    create: true
    owner: root
    group: root
    mode: 644
  when:
    - rhel_08_020040
  tags:
    - RHEL-08-020040

- name: MEDIUM | RHEL-08-020040 | RHEL 8 must enable a user session lock until that user re-establishes access using established identification and authentication
    procedures for command line sessions. Part 1 of 2
  ansible.builtin.lineinfile:
    path: /etc/tmux.conf
    line: bind X lock-session
    insertafter: set -g lock-command vlock
  when:
    - rhel_08_020040
  tags:
    - RHEL-08-020040
