---
- name: MEDIUM | RHEL-08-010550 | RHEL 8 must not permit direct logons to the root account using remote access via SSH.
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: ^#PermitRootLogin.*|^PermitRootLogin.*
    line: PermitRootLogin no
    state: present
    validate: /usr/sbin/sshd -tf %s
  notify: Restart OpenSSH

  when:
    - rhel_08_010550
  tags:
    - RHEL-08-010550
