---
- name: LOW | RHEL-08-030741 | RHEL 8 must disable the chrony daemon from acting as a server.
  ansible.builtin.lineinfile:
    path: /etc/chrony.conf
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  with_items:
    - { regexp: ^#log measurements statistics tracking, line: "" }
    - { regexp: ^#log measurements statistics tracking\n, line: "#Listening Port" }
    - { regexp: "^port [0-9]+|^#port [0-9]+", line: port 0 }
  notify: Restart Chrony

  when:
    - rhel_08_030741
    - not rhel8stig_timeserver
  tags:
    - RHEL-08-030741
