---
- name: LOW | RHEL-08-040021 | RHEL 8 must disable the asynchronous transfer mode (ATM) protocol.
  ansible.builtin.lineinfile:
    path: /etc/modprobe.d/blacklist.conf
    create: true
    owner: root
    group: root
    mode: 0644
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  with_items:
    - { regexp: "^#install (?i)atm.*|^install (?i)atm.*", line: install atm /bin/true }
    - { regexp: "^#blacklist (?i)atm", line: blacklist atm }

  when:
    - rhel_08_040021
  tags:
    - RHEL-08-040021
