---
- name: HIGH | RHEL-08-010440 | YUM must remove all software components after updated versions have been installed on RHEL 8.
  ansible.builtin.lineinfile:
    path: /etc/dnf/dnf.conf
    regexp: ^clean_requirements_on_remove = 0|^clean_requirements_on_remove=0|^clean_requirements_on_remove=False|^clean_requirements_on_remove = False|^clean_requirements_on_remove=no|^clean_requirements_on_remove
      = no|^#clean_requirements_on_remove=True
    line: clean_requirements_on_remove=True
    state: present

  when:
    - rhel_08_010440
  tags:
    - RHEL-08-010440
