---
- name: LOW | RHEL-08-010540 | MANUAL FIX | RHEL 8 must use a separate file system for /var.
  ansible.builtin.debug:
    msg: "Manual Lockdown Required | WARNING: /var is not mounted on a separate partition"
  changed_when: false

  when:
    - rhel_08_010540
    - ansible_mounts | selectattr('mount', 'match', '^/var$') | list | length == 0
  tags:
    - RHEL-08-010540
    - manual_fix
