---
- name: LOW | RHEL-08-030602 | RHEL 8 must allocate an audit_backlog_limit of sufficient size to capture processes that start prior to the audit daemon.
  ansible.builtin.command: grubby --update-kernel=ALL --args="audit_backlog_limit=8192"
  changed_when: false

  when:
    - rhel_08_030602
  tags:
    - RHEL-08-030602
