---
- name: LOW | RHEL-08-040024 | RHEL 8 must disable the transparent inter-process communication (TIPC) protocol.
  ansible.builtin.lineinfile:
    path: /etc/modprobe.d/blacklist.conf
    create: true
    owner: root
    group: root
    mode: 0644
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  with_items:
    - { regexp: "^#install (?i)tipc.*|^install (?i)tipc.*", line: install tipc /bin/true }
    - { regexp: "^#blacklist (?i)tipc", line: blacklist tipc }

  when:
    - rhel_08_040024
  tags:
    - RHEL-08-040024
