---
- name: LOW | RHEL-08-040310 | The RHEL 8 file integrity tool must be configured to verify Access Control Lists (ACLs).
  ansible.builtin.debug:
    msg: /etc/aide.conf acl is set by the AIDE role run through the Preliminary Tasks
  changed_when: false
  run_once: true

  when:
    - rhel_08_040310
  tags:
    - RHEL-08-040310
