---
- name: LOW | RHEL-08-010376 | RHEL 8 must prevent kernel profiling by unprivileged users.
  ansible.posix.sysctl:
    name: kernel.perf_event_paranoid
    value: "2"
    state: present
    sysctl_file: /etc/sysctl.d/99-sysctl.conf
    sysctl_set: true

  when:
    - rhel_08_010376
  tags:
    - RHEL-08-010376
