---
- name: LOW | RHEL-08-030601 | RHEL 8 must enable auditing of processes that start prior to the audit daemon.
  ansible.builtin.command: grubby --update-kernel=ALL --args="audit=1"
  changed_when: false

  when:
    - rhel_08_030601
  tags:
    - RHEL-08-030601
