---
- name: LOW | RHEL-08-010375 | RHEL 8 must restrict access to the kernel message buffer.
  ansible.posix.sysctl:
    name: kernel.dmesg_restrict
    value: "1"
    state: present
    sysctl_file: /etc/sysctl.d/99-sysctl.conf
    sysctl_set: true

  when:
    - rhel_08_010375
  tags:
    - RHEL-08-010375
