---
version: '3'

services:
  certbot:
    build: certbot-img/.  # Build custom certbot image with auto-renew enabled
    container_name: certbot
    restart: unless-stopped
    volumes:
      - ./data/letsencrypt:/etc/letsencrypt # Certificates
      - ./data/certbot-www:/var/www/certbot # For ACME challange

  nginx:
    image: nginx:1.23.4
    container_name: nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./data/nginx/conf.d:/etc/nginx/conf.d # NGINX reverse proxy configuration files
      - ./data/nginx/nginx-certbot.conf:/etc/nginx/nginx-certbot.conf # .well-known path for certbot
      - ./data/letsencrypt:/etc/letsencrypt:ro # Certificates from certbot
      - ./data/certbot-www:/var/www/certbot:ro # ACME challange files when certbot renews
