---
# tasks file for rhel8-stig
- name: Check OS version and family
  assert:
    that: ansible_os_family == 'RedHat' and ansible_distribution_major_version is version_compare('8', '==')
    msg: This role can only be run against RHEL/CENTOS 8. {{ ansible_distribution }} {{ ansible_distribution_major_version }} is not supported.
  tags:
    - always

- name: Check ansible version
  assert:
    that: ansible_version.full is version_compare(rhel8stig_min_ansible_version, '>=')
    msg: You must use Ansible {{ rhel8stig_min_ansible_version }} or greater
  tags:
    - always

- name: Include Prelim Tasks
  import_tasks: prelim.yml
  tags:
    - prelim_tasks
    - reboot_no
    - reboot_yes

- name: Include CAT I patches
  import_tasks: fix-cat1.yml
  when: rhel8stig_cat1_patch | bool
  tags:
    - cat1
    - high
    - reboot_no
    - reboot_yes

- name: Include CAT II patches
  import_tasks: fix-cat2.yml
  when: rhel8stig_cat2_patch | bool
  tags:
    - cat2
    - medium
    - reboot_no
    - reboot_yes

- name: Include CAT III patches
  import_tasks: fix-cat3.yml
  when: rhel8stig_cat3_patch | bool
  tags:
    - cat3
    - low
    - reboot_no
    - reboot_yes

- name: Execute Handlers
  meta: flush_handlers
  tags:
    - reboot_no
    - reboot_yes

- name: Reboot
  reboot:
    reboot_timeout: 900
    post_reboot_delay: 120
  tags:
    - never
    - reboot_yes
    - reboot_endpoints
  when:
    - not inventory_hostname == 'localhost'
    - not ansible_hostname == '{{ control_node }}'
  changed_when: false
