---
- block:
    - name: HIGH | RHEL-08-010470 | There must be no .shosts files on the RHEL 8 operating system. | Part 1 of 2
      ansible.builtin.find:
        paths: /
        pattern: "*.shosts"
        recurse: true
        hidden: true
      register: shosts_file_results

    - name: HIGH | RHEL-08-010470 | There must be no .shosts files on the RHEL 8 operating system. | Part 2 of 2
      ansible.builtin.file:
        path: "{{ item }}"
        state: absent
      with_items: "{{ shosts_file_results.files | map(attribute='path') | list  }}"
      when: shosts_file_results

  when:
    - rhel_08_010470
  tags:
    - RHEL-08-010470
