---
- block:
    - name: HIGH | RHEL-08-010020 | The Red Hat Enterprise Linux operating system must implement NIST FIPS-validated cryptography | Part 1 of 3
      ansible.builtin.dnf:
        name: fipscheck
        state: latest

    - name: HIGH | RHEL-08-010020 | The Red Hat Enterprise Linux operating system must implement NIST FIPS-validated cryptography | Part 2 of 3
      ansible.builtin.command: fipscheck
      register: fipscheck_result
      changed_when: false
      failed_when: fipscheck_result.rc !=2

    - name: HIGH | RHEL-08-010020 | The Red Hat Enterprise Linux operating system must implement NIST FIPS-validated cryptography | Part 3 of 3
      ansible.builtin.command: fips-mode-setup --enable
      when:
        - "'fips mode is on' not in fipscheck_result.stdout"
        - rhel8_fips_mode

  when:
    - rhel_08_010020
    - rhel8_fips_mode
  tags:
    - RHEL-08-010020
