---
- name: HIGH | RHEL-08-040190 | The Trivial File Transfer Protocol (TFTP) server package must not be installed if not required for RHEL 8 operational support.
  ansible.builtin.dnf:
    name: tftp-server
    state: absent
    autoremove: true

  when:
    - rhel_08_040190
    - not rhel8stig_requires_tftp
  tags:
    - RHEL-08-040190
